### ISSUE TITLE
Namecheap as a Provider

### ISSUE THREAD

**Issue by maelgangloff** [maelgangloff/domain-watchdog#22]
Documentation : https://www.namecheap.com/support/api/methods/domains/create

**Comment by maelgangloff** [comment]
Resolved in #51

**Comment by AlejandroAkbal** [comment]
Im getting this error: 
![image](https://github.com/user-attachments/assets/28924c8a-7d05-44c8-8f3f-c2d845033f8c)
when creating a namecheap connector

**Comment by vinceh121** [comment]
> Im getting this error: 
> ![image](https://github.com/user-attachments/assets/28924c8a-7d05-44c8-8f3f-c2d845033f8c)
> when creating a namecheap connector

Apologies for the lack of documentation about this, but Namecheap requires that we communicate the outgoing IP address at every API call.
As a result, you need to set the environment variable OUTGOING_IP to your public IP.
Also remember to whitelist this same IP address in your Namecheap settings.
