### ISSUE TITLE
ARM64 docker image version

### ISSUE THREAD

**Issue by AlejandroAkbal** [maelgangloff/domain-watchdog#43]
Hey, Im trying to run this on ARM and I get this error:

`php-worker The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested `

Could you please enable releasing ARM versions besides AMD64?

**Comment by maelgangloff** [comment]
Hey, I updated the workflow for publishing to [Docker Hub](https://hub.docker.com/r/maelgangloff/domain-watchdog).
The Docker image is now available for arm64 platforms. Future builds will be for both amd64 and arm64 platforms.
