### ISSUE TITLE
Add more options for watchlist webhook DSN

### ISSUE THREAD

**Issue by anarion80** [maelgangloff/domain-watchdog#50]
So far I tried two: `smtp` and `pushover` and in both cases there was an error:

`The DSN scheme (smtp) is not supported`
`The DSN scheme (pushover) is not supported`

**Comment by vinceh121** [comment]
smtp is currently not supported as a webhook DSN as it is handled separatly, you will get an email to the address specified in your user account for the select events in the watchlist.

pushover, however, can absolutly be added.

**Comment by maelgangloff** [comment]
Email notifications are always enabled by default. Webhook notifications are optional.
I will add support for `pushover`.

**Comment by maelgangloff** [comment]
@anarion80 I just added the dependencies needed to link with `pushover`. I let you tell me if it works now.

This is what the DSN looks like according to the Symfony documentation:
```txt
pushover://USER_KEY:APP_TOKEN@default
```
For you to test, I deployed the v0.2.6 version which is already available on the Docker Hub ;)

**Comment by maelgangloff** [comment]
It seems I rushed, Symfony separates Chat from Push notifications...
I'll post here when I've made a working implementation.

**Comment by maelgangloff** [comment]
I just corrected my mistake :)

**Comment by anarion80** [comment]
Thanks! I was able to add pushover successfully and receive a test notification.
