### ISSUE TITLE
New Docker release

### ISSUE THREAD

**Issue by daerup** [maelgangloff/domain-watchdog#54]
Could you release a new docker image that includes the new providers?

**Comment by maelgangloff** [comment]
Hello @daerup,
I just released v0.4.0. Docker images are being built from source.
Let me know if you have any issues with them.

**Comment by daerup** [comment]
Hi, just deployed the newest version. When adding the namecheap connectons, an error pops up regarding ClientIP: client![IMG_20241031_224617.jpg](https://github.com/user-attachments/assets/26705808-9eb5-44f6-9c1f-f465c193c79e)

**Comment by vinceh121** [comment]
Apologies for the lack of documentation about this, but Namecheap requires that we communicate the outgoing IP address at every API call.
As a result, you need to set the environment variable `OUTGOING_IP` to your public IP.
Also remember to whitelist this same IP address in your Namecheap settings.

**Comment by daerup** [comment]
Great thank you, now it works! Do you perhaps know if there is a setting for max purchase price? Also is it possible to test the connector, so that in case the domain becomes available everything works out?


I also notices that some TLD do not work (.ch for example). Is there anything I can do?

**Comment by vinceh121** [comment]
> Do you perhaps know if there is a setting for max purchase price?

There currently isn't. Although if the domain is at a premium price, it won't be bought.

> Also is it possible to test the connector, so that in case the domain becomes available everything works out?

While Namecheap's sandbox environment is implemented, when I developed the connector it wasn't running properly altogether. You *may* be able to test the sandbox by setting your `env` to `dev`. Of course, don't keep this in production afterwards.

**Comment by daerup** [comment]
Perfect thank you! Btw. its not possible to monitor `.io` right? Just making sure..

**Comment by vinceh121** [comment]
The registry behind .io currently doesn't have RDAP support. You can see the deployment status here: [https://deployment.rdap.org/](https://deployment.rdap.org/)

By premium price I mean buying premium domains.

A premium domain is either:
- a domain that's being resold through the registrar, usually at a high price
- a domain that's short, or comprised of only a common word, also sold at a high price
